name: test

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install and Update Essential Dependencies
      run: |
        pip install -U pip setuptools
        pip install tox-gh-actions
    - name: Run Repository Tests
      run: |
        tox
    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_SECRET }}
        files: coverage.xml
        verbose: true
